work around access denied issue on windows in github actions when running `cargo clean`
error: failed to remove build artifact

Caused by:
  failed to remove file `D:\a\rusty\rusty\target\debug\deps\xtask.exe`

Caused by:
  Access is denied. (os error 5)